name: terraform-ci
on:
  pull_request:
permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@v2
    with:
      upload_sarif: false
      # skip_tflint_warn: false
      # default_runner_override_label: self-hosted
      # runner_label: platform-eng
