name: terraform-ci
on:
  pull_request:
  push:
    branches:
      - local-skip-test
# permissions:
#   actions: read
#   checks: read
#   contents: read
#   pull-requests: read
#   security-events: write
jobs:
  ci:
    uses: ./.github/workflows/terraform.yaml
    with:
      upload_sarif: false
    secrets: inherit
